"""Criar tabela de vendas e clientes

Revision ID: aae960b1eaaf
Revises: f5fce5e39838
Create Date: 2026-06-02 10:07:41.579579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae960b1eaaf'
down_revision: Union[str, Sequence[str], None] = 'f5fce5e39838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
